### ISSUE TITLE
Binary XML file line #44 in com.kannikesh.torrflixbeta:layout/activity_home: Error inflating class com.iammert.library.readablebottombar.ReadableBottomBar

### ISSUE THREAD

**Issue by kannikesh** [iammert/ReadableBottomBar#20]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.kannikesh.torrflixbeta, PID: 13017
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.kannikesh.torrflixbeta/com.kannikesh.torrflixbeta.HomeActivity}: android.view.InflateException: Binary XML file line #44 in com.kannikesh.torrflixbeta:layout/activity_home: Binary XML file line #44 in com.kannikesh.torrflixbeta:layout/activity_home: Error inflating class com.iammert.library.readablebottombar.ReadableBottomBar
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3311)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3460)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2047)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7590)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: android.view.InflateException: Binary XML file line #44 in com.kannikesh.torrflixbeta:layout/activity_home: Binary XML file line #44 in com.kannikesh.torrflixbeta:layout/activity_home: Error inflating class com.iammert.library.readablebottombar.ReadableBottomBar
     Caused by: android.view.InflateException: Binary XML file line #44 in com.kannikesh.torrflixbeta:layout/activity_home: Error inflating class com.iammert.library.readablebottombar.ReadableBottomBar
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:858)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:696)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:170)
        at com.kannikesh.torrflixbeta.HomeActivity.onCreate(HomeActivity.java:28)
        at android.app.Activity.performCreate(Activity.java:7893)
        at android.app.Activity.performCreate(Activity.java:7880)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3286)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3460)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2047)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7590)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x0
E/AndroidRuntime:     at android.content.res.Resources.getText(Resources.java:381)
        at android.content.res.MiuiResources.getText(MiuiResources.java:97)
        at android.content.res.Resources.getString(Resources.java:474)
        at android.content.Context.getString(Context.java:648)
        at com.iammert.library.readablebottombar.ConfigurationXmlParser.getText(ConfigurationXmlParser.kt:49)
        at com.iammert.library.readablebottombar.ConfigurationXmlParser.getTabConfig(ConfigurationXmlParser.kt:37)
        at com.iammert.library.readablebottombar.ConfigurationXmlParser.parse(ConfigurationXmlParser.kt:21)
        at com.iammert.library.readablebottombar.ReadableBottomBar.<init>(ReadableBottomBar.kt:72)
        at com.iammert.library.readablebottombar.ReadableBottomBar.<init>(ReadableBottomBar.kt:12)
        at com.iammert.library.readablebottombar.ReadableBottomBar.<init>(Unknown Source:6)
        	... 28 more

**Comment by Lemou-Memo** [comment]
String resource ID #0x0，我也遇到了这个bug

**Comment by Lemou-Memo** [comment]
This is not about AndroidX. I created a new project and implemented the library via Gradle. Everything was perfect. Also, I reproduced your crash.

If you create tab item following everything is fine:

```
<tab
    drawable="@drawable/ic_home_black_24dp"
    text="@string/home" />
```
But if you create like this:

```
<tab
    drawable="@drawable/ic_home_black_24dp"
    text="Home" />
```
It throws the error. Please recheck your tabs file.

copy to the closed issues that called “error”
