### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by nowfalsalahudeen** [iammert/ReadableBottomBar#4]
--------- beginning of crash
2019-03-14 12:06:55.515 9134-9134/com.vtoqa.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.vtoqa.app, PID: 9134
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.vtoqa.app/com.vtoqa.app.activity.Home.VtoqaHomeUpdatedActivity}: android.view.InflateException: Binary XML file line #10: Binary XML file line #10: Error inflating class com.iammert.library.readablebottombar.ReadableBottomBar
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: android.view.InflateException: Binary XML file line #10: Binary XML file line #10: Error inflating class com.iammert.library.readablebottombar.ReadableBottomBar
     Caused by: android.view.InflateException: Binary XML file line #10: Error inflating class com.iammert.library.readablebottombar.ReadableBottomBar
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
        at com.vtoqa.app.activity.Home.VtoqaHomeUpdatedActivity.onCreate(VtoqaHomeUpdatedActivity.kt:11)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x0
        at android.content.res.Resources.getText(Resources.java:348)
        at android.content.res.Resources.getString(Resources.java:441)
        at android.content.Context.getString(Context.java:578)
        at com.iammert.library.readablebottombar.ConfigurationXmlParser.getText(ConfigurationXmlParser.kt:49)
2019-03-14 12:06:55.515 9134-9134/com.vtoqa.app E/AndroidRuntime:     at com.iammert.library.readablebottombar.ConfigurationXmlParser.getTabConfig(ConfigurationXmlParser.kt:37)
        at com.iammert.library.readablebottombar.ConfigurationXmlParser.parse(ConfigurationXmlParser.kt:21)
        at com.iammert.library.readablebottombar.ReadableBottomBar.<init>(ReadableBottomBar.kt:60)
        at com.iammert.library.readablebottombar.ReadableBottomBar.<init>(ReadableBottomBar.kt:10)
        at com.iammert.library.readablebottombar.ReadableBottomBar.<init>(Unknown Source:6)
        	... 28 more
2019-03-14 12:06:55.524 9134-9168/com.vtoqa.app V/FA: Connecting to remote service
2019-03-14 12:06:55.530 9134-9168/com.vtoqa.app V/FA: Connection attempt already in progress
2019-03-14 12:06:59.516 9134-9134/com.vtoqa.app E/CrashlyticsCore: Failed to execute task.
    java.util.concurrent.TimeoutException
        at java.util.concurrent.FutureTask.get(FutureTask.java:206)
        at com.crashlytics.android.core.CrashlyticsBackgroundWorker.submitAndWait(CrashlyticsBackgroundWorker.java:41)
        at com.crashlytics.android.core.CrashlyticsController.handleUncaughtException(CrashlyticsController.java:321)
        at com.crashlytics.android.core.CrashlyticsController$6.onUncaughtException(CrashlyticsController.java:301)
        at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.uncaughtException(CrashlyticsUncaughtExceptionHandler.java:42)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
        at java.lang.Thread.dispatchUncaughtException(Thread.java:1955)
2019-03-14 12:06:59.517 9134-9134/com.vtoqa.app E/UncaughtException: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.vtoqa.app/com.vtoqa.app.activity.Home.VtoqaHomeUpdatedActivity}: android.view.InflateException: Binary XML file line #10: Binary XML file line #10: Error inflating class com.iammert.library.readablebottombar.ReadableBottomBar
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: android.view.InflateException: Binary XML file line #10: Binary XML file line #10: Error inflating class com.iammert.library.readablebottombar.ReadableBottomBar
     Caused by: android.view.InflateException: Binary XML file line #10: Error inflating class com.iammert.library.readablebottombar.ReadableBottomBar
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
        at com.vtoqa.app.activity.Home.VtoqaHomeUpdatedActivity.onCreate(VtoqaHomeUpdatedActivity.kt:11)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x0
        at android.content.res.Resources.getText(Resources.java:348)
        at android.content.res.Resources.getString(Resources.java:441)
        at android.content.Context.getString(Context.java:578)
        at com.iammert.library.readablebottombar.ConfigurationXmlParser.getText(ConfigurationXmlParser.kt:49)
2019-03-14 12:06:59.517 9134-9134/com.vtoqa.app E/UncaughtException:     at com.iammert.library.readablebottombar.ConfigurationXmlParser.getTabConfig(ConfigurationXmlParser.kt:37)
        at com.iammert.library.readablebottombar.ConfigurationXmlParser.parse(ConfigurationXmlParser.kt:21)
        at com.iammert.library.readablebottombar.ReadableBottomBar.<init>(ReadableBottomBar.kt:60)
        at com.iammert.library.readablebottombar.ReadableBottomBar.<init>(ReadableBottomBar.kt:10)
        at com.iammert.library.readablebottombar.ReadableBottomBar.<init>(Unknown Source:6)
        	... 28 more

**Comment by andanicalik** [comment]
> Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x0

Are you sure you prepared xml file like in the example project?

https://github.com/iammert/ReadableBottomBar/blob/master/app/src/main/res/xml/tabs.xml

**Comment by nowfalsalahudeen** [comment]
yes.same as your exact copy..but my project was on android X artifact..

**Comment by jobayerjim9** [comment]
Same problem! Using AndroidX

**Comment by andanicalik** [comment]
This is not about AndroidX. I created a new project and implemented this library via Gradle. Everything was perfect. Also, I reproduced the above crash.

If you create tab item like following, everything is fine:

<tab
    drawable="@drawable/ic_home_black_24dp"
    text="@string/home" />

But if you create like this:

<tab
    drawable="@drawable/ic_home_black_24dp"
    text="Home" />

It throws the error. Please recheck your tabs file.

**Comment by andanicalik** [comment]
This is not about AndroidX. I created a new project and implemented the library via Gradle. Everything was perfect. Also, I reproduced your crash.

If you create tab item following everything is fine:

```
<tab
    drawable="@drawable/ic_home_black_24dp"
    text="@string/home" />
```

But if you create like this:

```
<tab
    drawable="@drawable/ic_home_black_24dp"
    text="Home" />
```

It throws the error. Please recheck your tabs file.

**Comment by jobayerjim9** [comment]
<tab
    drawable="@drawable/ic_home_black_24dp"
    text="@string/home" />
this saved me. Thanks!

**Comment by nowfalsalahudeen** [comment]
will check it.. thanks for your update
